apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-admin
  labels:
    app: store-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-admin
  template:
    metadata:
      labels:
        app: store-admin
    spec:
      containers:
      - name: store-admin
        image: zeelu1/store-admin:latest
        ports:
        - containerPort: 3001
        env:
        - name: NEXT_PUBLIC_PRODUCT_API_URL
          valueFrom:
            configMapKeyRef:
              name: store-admin-config
              key: NEXT_PUBLIC_PRODUCT_API_URL
        - name: NEXT_PUBLIC_AI_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: store-admin-config
              key: NEXT_PUBLIC_AI_SERVICE_URL
        - name: NEXT_PUBLIC_MAKELINE_API_URL
          valueFrom:
            configMapKeyRef:
              name: store-admin-config
              key: NEXT_PUBLIC_MAKELINE_API_URL
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5 