apiVersion: v1
kind: Service
metadata:
  name: ai-service
spec:
  selector:
    app: ai-service
  ports:
    - protocol: TCP
      port: 3080
      targetPort: 3080
  type: ClusterIP

---



apiVersion: v1
kind: Service
metadata:
  name: makeline-service
spec:
  selector:
    app: makeline-service
  ports:
    - name: api
      protocol: TCP
      port: 3070
      targetPort: 3070
  type: ClusterIP 

---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 3050
      targetPort: 3050
  type: ClusterIP 

---
apiVersion: v1
kind: Secret
metadata:
  name: product-service-secrets
type: Opaque
data:
  MONGO_USERNAME: ""
  MONGO_PASSWORD: ""
  COSMOS_DB_CONNECTION_STRING: ""

---
apiVersion: v1
kind: Service
metadata:
  name: store-admin
  labels:
    app: store-admin
spec:
  type: LoadBalancer
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
  selector:
    app: store-admin 

---
apiVersion: v1
kind: Service
metadata:
  name: store-front
  labels:
    app: store-front
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: store-front 






