apiVersion: v1
kind: Service
metadata:
  name: store-front
  labels:
    app: store-front
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: store-front 