apiVersion: v1
kind: Service
metadata:
  name: store-admin
  labels:
    app: store-admin
spec:
  type: LoadBalancer
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
  selector:
    app: store-admin 