apiVersion: v1
kind: Secret
metadata:
  name: makeline-secrets
  namespace: default
type: Opaque
data:
  cosmos-db-connection-string: ""
  service-bus-connection-string: ""
  service-bus-queue-name: "" 