apiVersion: v1
kind: ConfigMap
metadata:
  name: store-admin-config
data:
  NEXT_PUBLIC_PRODUCT_API_URL: "http://product-service:3060"
  NEXT_PUBLIC_AI_SERVICE_URL: "http://ai-service:3080"
  NEXT_PUBLIC_MAKELINE_API_URL: "http://makeline-service:3070" 